---
- name: Upgrades and Dist-Upgrades servers
  hosts: all
  tasks:
  - name: Update apt
    shell: apt-get -y update
    register: apt_result
  - name: Make a general dist-upgrade
    shell: apt-get -y dist-upgrade
    register: apt_result
  - name: Remove old packages
    shell: apt-get -y autoremove
    register: apt_result
