---
- name: Upgrades and Dist-Upgrades servers
  hosts: all
  remote_user: "{{user}}"
  become: true
  become_user: root
  tasks:
  - name: Update apt
    apt: update_cache=yes
  - name: Make a general dist-upgrade
    apt: upgrade=dist
